name: Build SDist

on:
  - push
  - pull_request

jobs:
  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.8"

      - name: Install build package
        run: python -m pip install build

      - name: Build source distribution
        run: python -m build --sdist --outdir dist/

      - name: Upload source distribution
        uses: actions/upload-artifact@v4
        with:
          name: source-distribution
          path: dist/*.tar.gz
