publish:
  name: Publish package
  if: startsWith(github.event.ref, 'refs/tags/v')
  needs:
    - build_source_dist
    - build_wheels
  runs-on: ubuntu-latest

  steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: ./dist/

    - uses: pypa/gh-action-pypi-publish@1.5.0
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
